* conventional-commit.el
#+begin_html
<a href="https://github.com/akirak/conventional-commit.el/actions?query=workflow%3A%22CI%22">
<img alt="CI Status" src="https://github.com/akirak/conventional-commit.el/workflows/CI/badge.svg" />
</a>
#+end_html
This library provides support for [[https://www.conventionalcommits.org/en/v1.0.0/][conventional commits]] in Emacs.
It provides a completion function for types and scopes.
** Installation
This package is not available on any popular package registry yet.
** Configuration
This package provides =conventional-commit-setup= function which enables completion via =completion-at-point-functions= locally.
If you are a user of =use-package=, you can use the following snippet:

#+begin_src emacs-lisp
  (use-package conventional-commit
    :hook
    (git-commit-mode . conventional-commit-setup))
#+end_src

If you are using [[https://github.com/company-mode/company-mode][company-mode]] for completion, you have to add =company-capf= to =company-backends= (you should be already doing this if you are a user of =eglot= or =lsp-mode=):

#+begin_src emacs-lisp
  (add-hook 'company-backends #'company-capf)
#+end_src

To configure the list of types, customize =conventional-commit-type-list= variable.

To configure scopes, set =conventional-commit-scope-table= in =.dir-locals.el= of your project.
